## 1. Question 1

Use the EDHEC Hedge Fund Indices data set that we used in the lab assignment as well as in the previous week’s assignments. Load them into Python and perform the following analysis based on data since 2000 (including all of 2000): What was the Monthly Parametric Gaussian VaR at the 1% level (as a +ve number) of the Distressed Securities strategy?
Enter the positive number as a percent .e.g. For 5.32% enter 5.32
NOTE: You may either round or truncate to 1 decimal place, we will accept either answer


In [20]:
import pandas as pd
import numpy as np

In [13]:
import pandas as pd
import edhec_risk_kit_118 as erk
%load_ext autoreload
%autoreload 2
%matplotlib inline

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [14]:
hfi = erk.get_hfi_returns()

In [15]:
hfi2000 = hfi["2000":]

In [16]:
import numpy as np
np.percentile(hfi, a=0.01)

TypeError: _percentile_dispatcher() got multiple values for argument 'a'

In [17]:
erk.var_historic(hfi2000, level=1)

Convertible Arbitrage     0.031674
CTA Global                0.050938
Distressed Securities     0.042642
Emerging Markets          0.065496
Equity Market Neutral     0.019800
Event Driven              0.038540
Fixed Income Arbitrage    0.030748
Global Macro              0.022632
Long/Short Equity         0.045060
Merger Arbitrage          0.022654
Relative Value            0.021788
Short Selling             0.107684
Funds Of Funds            0.027200
dtype: float64

In [18]:
from scipy.stats import norm
norm.ppf(.5)

0.0

In [19]:
norm.ppf(.16)

-0.994457883209753

In [20]:
erk.var_gaussianCF(hfi2000["Distressed Securities"])

AttributeError: module 'edhec_risk_kit_118' has no attribute 'var_gaussianCF'

In [21]:
#### 3.14

## 2. Question 2

Use the same data set at the previous question. What was the 1% VaR for the same strategy after applying the Cornish-Fisher Adjustment?
Enter the answer as a positive number, in percent terms. e.g. for 5.32% enter 5.32


In [22]:
erk.var_gaussianCF(hfi2000["Distressed Securities"])

AttributeError: module 'edhec_risk_kit_118' has no attribute 'var_gaussianCF'

In [23]:
4.96

4.96

## 3. Question 3
Use the same dataset as the previous question. What was the Monthly Historic VaR at the 1% level (as a +ve number) of the Distressed Securities strategy?
Enter the answer as a positive number, in percent terms. e.g. for 5.32% enter 5.32


In [24]:
erk.var_historic(hfi2000["Distressed Securities"])

0.019579999999999997

In [72]:
4.26


4.26

## 4. Question 4
Next, load the 30 industry return data using the erk.get_ind_returns() function that we developed during the lab sessions. For purposes of the remaining questions, use data during the 5 year period 2013-2017 (both inclusive) to estimate the expected returns as well as the covariance matrix. To be able to respond to the questions, you will need to build the MSR, EW and GMV portfolios consisting of the “Books”, “Steel”, "Oil", and "Mines" industries. Assume the risk free rate over the 5 year period is 10%.
What is the weight of Steel in the EW Portfolio?
Enter the answer in percent terms rounded to one decimal place. e.g. for 5.32% enter 5.3


In [1]:
import edhec_risk_kit_111 as erk
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
ind = erk.get_ind_returns()

In [3]:
l = ["Books", "Steel", "Oil", "Mines"]
ind = ind[l]

In [4]:
ind.head()

Books   Steel     Oil   Mines
1926-07  0.1097  0.0407 -0.0140  0.0564
1926-08  0.1001  0.0217  0.0369  0.0055
1926-09 -0.0099  0.0015 -0.0369  0.0174
1926-10  0.0947 -0.0385 -0.0104 -0.0320
1926-11 -0.0580  0.0386  0.0006  0.0846

In [5]:
1/4*100

25.0

In [6]:
25

25

What is the weight of the largest component of the MSR portfolio?   

Enter the answer in percent terms rounded to one decimal place. e.g. for 5.32% enter 5.3

5.
Question 5

What is the weight of the largest component of the MSR portfolio?   

In [7]:
er = erk.annualize_rets(ind["2013":"2017"], 12)

In [8]:
cov = ind["2013":"2017"].cov()

In [9]:
riskfree_rate = 0.1

In [10]:
msr_w = erk.msr(riskfree_rate, er, cov)
round(msr_w.max()*100,2)

100.0

In [11]:
msr_w

array([1.46306578e-14, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00])

6.
Question 6

Which of the 4 components has the largest weight in the MSR portfolio?

In [12]:
l = ["Books", "Steel", "Oil", "Mines"]

In [14]:
l[erk.msr(riskfree_rate, er, cov).argmax(axis=0)]

'Steel'

In [15]:
# Steel

7.
Question 7

How many of the components of the MSR portfolio have non-zero weights?  

In [16]:
1

1

8.
Question 8

What is the weight of the largest component of the GMV portfolio?

In [17]:
erk.gmv(cov)

array([4.77024858e-01, 2.38524478e-18, 4.34112041e-01, 8.88631011e-02])

In [21]:
np.round([erk.gmv(cov).max(axis=0)*100],2)

array([47.7])

In [22]:
47.70

47.7

9.
Question 9

Which of the 4 components has the largest weight in the GMV portfolio?    

In [23]:
l[erk.gmv(cov).argmax(axis=0)]

'Books'

In [24]:
# Books

10.
Question 10

 How many of the components of the GMV portfolio have non-zero weights?    

In [25]:
gmv_wgts = erk.gmv(cov)

In [28]:
len(gmv_wgts[gmv_wgts > 0.001])

3

In [82]:
3

3

11.
Question 11

Assume two different investors invested in the GMV and MSR portfolios at the start of 2018 using the weights we just computed. Compute the annualized volatility of these two portfolios over the next 12 months of 2018? (Hint: Use the portfolio_vol code we developed in the lab and use ind[“2018”][l].cov() to compute the covariance matrix for 2018, assuming that the variable ind holds the industry returns and the variable l holds the list of industry portfolios you are willing to hold. Don’t forget to annualize the volatility)

In [34]:
covmat = ind["2018"].cov()

/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  """Entry point for launching an IPython kernel.


In [38]:
erk.portfolio_vol(msr_w, cov_1) * np.sqrt(12)*100 

21.98398818148407

12.
Question 12

What would be the annualized volatility over 2018 using the weights of the GMV portfolio? (Reminder and Hint: Use the portfolio_vol code we developed in the lab and use ind[“2018”][l].cov() to compute the covariance matrix for 2018, assuming that the variable ind holds the industry returns and the variable l holds the list of industry portfolios you are willing to hold. Don’t forget to annualize the volatility) 

Enter the answer in percent terms. e.g. for 5.32% enter 5.32

In [37]:
erk.portfolio_vol(gmv_wgts, cov_1) * np.sqrt(12)*100

18.97373464872575